In [6]:
import numpy as np

1. Create a NumPy array

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
arr=np.array([2,5,7,9,5])
print(arr)

[2 5 7 9 5]


2. Create an array of zeros

In [9]:
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


3. Create an array of ones

In [10]:
o=np.ones(5)
print(o)

[1. 1. 1. 1. 1.]


4. Create numbers from 1 to 10

In [11]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


5. Reshape array into 2 rows and 5 columns

In [12]:
arr=np.arange(1,11)
reshaped=arr.reshape(2,5)
print(reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


6. Create a 3x3 matrix

In [13]:
matrix=np.arange (1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7. Add two arrays
8. Subtract arrays
9. Multiply arrays
10. Divide arrays

In [14]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


11. Find mean of array

In [15]:
arr=np.array([10,20,30,40])
print(np.mean(arr))

25.0


12. Find sum of array

In [16]:
print(np.sum(arr))

100


13. Find maximum and minimum value

In [17]:
print(np.max(arr))
print(np.min(arr))

40
10


13. Find maximum and minimum value

In [18]:
arr=np.arange(1,11)
print(arr[0:5])

[1 2 3 4 5]


15. Get elements greater than 5

In [19]:
print(arr[arr>5])

[ 6  7  8  9 10]


16. Change specific value

In [20]:
arr[0]=100
print(arr)

[100   2   3   4   5   6   7   8   9  10]


17. Create random array

In [21]:
random=np.random.rand(5)
print(random)

[0.42145612 0.76762506 0.88855161 0.76543885 0.62460943]


18. Create identity matrix

In [22]:
ide=np.eye(10)
print(ide)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


19. Matrix multiplication using dot()

In [23]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(np.dot(a,b))

[[ 7 10]
 [15 22]]


20. Find shape of array

In [24]:
arr=np.arange(12).reshape(3,4)
print(arr.shape)

(3, 4)


21. Flatten a matrix -means shape are convert into in a single line

In [25]:
flat=arr.flatten()
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


22. Find transpose of matrix-- means utlta kar deta hai ky agr smajho 2,4 hai to print(arr.T) use karne se 4,2 ho jayega

In [26]:
print(arr.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


23. Find average of rows

In [27]:
matrix=np.array([[1,2],[3,4]])
print(np.mean(matrix, axis=1))

[1.5 3.5]


24. Find sum of columns

In [28]:
print(np.sum(matrix,axis=0))

[4 6]


25. Boolean indexing

In [29]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[arr%2==0])

[2 4 6 8]


new question

1. Create array from 10 to 20

In [30]:
arr=np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


2. Find even numbers

In [31]:
arr=np.arange(1,21)
print(arr[arr% 2==0])

[ 2  4  6  8 10 12 14 16 18 20]


3. Multiply all elements by 5

In [32]:
arr=np.array([1,2,3,4,5])
print(arr*5)

[ 5 10 15 20 25]


4. Create 4x4 matrix

In [33]:
arr=np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


5. Print first row

In [34]:
print(arr[0])

[1 2 3 4]


6. Print second column

In [35]:
print(arr[:,1])

[ 2  6 10 14]


7. Find numbers greater than 10

In [36]:
print (arr[arr>10])

[11 12 13 14 15 16]


8. Find total sum

In [37]:
print(np.sum(arr))

136


9. Find row-wise sum

In [38]:
print(np.sum(arr,axis=1))

[10 26 42 58]


10. Find column-wise sum

In [39]:
print(np.sum(arr,axis=0))

[28 32 36 40]
